# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-24 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthQQUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('openid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_oauth_qq',
            },
        ),
    ]
